---
- name: Install Apache
  apt:
    name: apache2
    state: latest
- name: Enable rewrite module
  command: a2enmod rewrite
- name: Allow port 80 through firewall
  ufw:
    rule: allow
    port: "{{ apache_port }}"
    proto: tcp
