---
- name: Add ppa:ondrej/php repository
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true
- name: Install PHP 8.2
  apt:
    name:
      - php8.2
      - php8.2-common
      - php8.2-bz2
      - php8.2-cli
      - php8.2-curl
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-mysql
      - php8.2-xml
      - php8.2-zip
      - libapache2-mod-php8.2
    state: present
