---
- name: Add ppa:ondrej/php repository
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true
- name: Install PHP 8.3
  apt:
    name:
      - php8.3
      - php8.3-common
      - php8.3-bz2
      - php8.3-cli
      - php8.3-curl
      - php8.3-intl
      - php8.3-mbstring
      - php8.3-mysql
      - php8.3-xml
      - php8.3-zip
      - libapache2-mod-php8.3
    state: present
