---
- name: Add ppa:ondrej/php repository
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true
- name: Install PHP 8.1
  apt:
    name:
      - php8.1
      - php8.1-common
      - php8.1-bz2
      - php8.1-cli
      - php8.1-curl
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-xml
      - php8.1-zip
      - libapache2-mod-php8.1
    state: present
