---
- name: Install Apache
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
- name: Enable rewrite module
  command: a2enmod rewrite
- name: Allow port 80 through firewall
  ufw:
    rule: allow
    port: "80"
    proto: tcp
