---
- name: Install PHP and common modules
  package:
    name:
      - php7.4
      - php7.4-common
      - php7.4-bz2
      - php7.4-cli
      - php7.4-curl
      - php7.4-intl
      - php7.4-json
      - php7.4-mbstring
      - php7.4-xml
      - php7.4-zip
    state: latest
- name: Create info.php file
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
