---
- name: Add Node.js 20.x repo
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  args:
    warn: no
- name: Install Node.js 20.x
  apt:
    name: nodejs
    state: latest
