---
- name: Create destination directory
  file:
    path: "{{ phpmyadmin_dest_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Download PhpMyAdmin
  unarchive:
    src: "{{ phpmyadmin_download_url }}"
    dest: "{{ phpmyadmin_dest_dir }}"
    remote_src: yes
- name: Create /tmp directory for PhpMyAdmin
  file:
    path: "{{ phpmyadmin_dest_dir }}/tmp"
    state: directory
    owner: root
    group: root
    mode: 0777
- name: Configure PhpMyAdmin
  template:
    src: phpmyadmin.conf.j2
    dest: "{{ phpmyadmin_apache_config_file }}"
