---
- name: Install MySQL
  apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pymysql
    state: latest
- name: Assign home directory
  command: usermod -d /var/lib/mysql/ mysql
- name: Start and enable MySQL
  service:
    name: mysql
    state: restarted
    enabled: true
- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ config.mysql.root_password }}"
    login_unix_socket: "{{ login_unix_socket }}"
  no_log: true
- name: Configure login socket location
  template:
    src: my.cnf.j2
    dest: "{{ mysql_mycnf_dest }}"
  notify: Restart MySQL
