---
- name: Start Apache
  service:
    name: apache2
    state: started
- name: Stop Apache
  service:
    name: apache2
    state: stopped
- name: Restart Apache
  service:
    name: apache2
    state: restarted
- name: Reload Apache
  service:
    name: apache2
    state: reloaded
