---
- name: Install PHP 7.2
  dnf:
    name:
      - php
      - php-common
      - php-cli
      - php-intl
      - php-json
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-xml
    state: latest
