---
- name: Install PhpMyAdmin
  apt:
    name: phpmyadmin
    state: latest
- name: Add PhpMyAdmin config to Apache config
  blockinfile:
    path: "{{ apache_config_file }}"
    insertafter: IncludeOptional sites-enabled/*.conf
    block: |
      # Include phpmyadmin config
      IncludeOptional "{{ phpmyadmin_apache_config_file }}"
