---
- name: Create MariaDB 10.11 repo file
  template:
    src: "{{ mariadb_repo_src }}"
    dest: "{{ mariadb_repo_dest }}"
    owner: "{{ config.system.username }}"
    group: "{{ config.system.username }}"
- name: Install MariaDB 10.11
  command: "dnf install python3-mysqlclient MariaDB-server MariaDB-client -y"
- name: Enable and start MariaDB service
  command: systemctl enable --now mariadb
- name: Set MariaDB root password
  mysql_user:
    login_user: root
    login_password: "{{ config.mariadb.root_password }}"
    check_implicit_admin: true
    user: root
    password: "{{ config.mariadb.root_password }}"
    host: localhost
