---
- name: Start MySQL
  service:
    name: mysqld
    state: started
- name: Stop MySQL
  service:
    name: mysqld
    state: stopped
- name: Restart MySQL
  service:
    name: mysqld
    state: restarted
- name: Enable MySQL
  service:
    name: mysqld
    enabled: yes
