---
- name: Setup new development environment
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - config.yml
  roles:
    - packages
    - apache
    - mysql
    - php
    - phpmyadmin
    - composer
    - git
