---
- name: Update/Upgrade installed packages
  dnf:
    name: "*"
    state: latest
    update_cache: true
- name: Install requirements
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - firewalld
- name: Copy WSL configuration file
  template:
    src: wsl.conf.j2
    dest: "{{ wsl_config_dest }}"
- name: Copy .bash_profile file
  template:
    src: bash_profile.j2
    dest: "{{ bash_profile_dest }}"
