---
- name: Install selected PHP versions
  include_role:
    name: php
    tasks_from: "php{{ php_version }}"
  loop: "{{ config.php.versions }}"
  loop_control:
    loop_var: php_version
- name: Create PHP info file
  template:
    src: "{{ php_info_filename }}.j2"
    dest: "{{ apache_home_dir }}/{{ php_info_filename }}"
  notify: Restart Apache
