---
- name: Install PHP 7.4
  apt:
    name:
      - php7.4
      - php7.4-common
      - php7.4-bz2
      - php7.4-cli
      - php7.4-curl
      - php7.4-intl
      - php7.4-json
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-xml
      - php7.4-zip
      - libapache2-mod-php7.4
    state: present
